eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8700
spring:
  application:
    name: catj-zuul
  sleuth:
    sampler:
      percentage: 1
  zipkin:
      base-url: http://localhost:7740

zuul:
  routes:
    user:
      path: /api-user/**
      service-id: user-service
      path: /api-cas/**
      service-id: catj-cas

