server:
  # 端口
  port: 8083

feign:
  hystrix:
    enabled: true # 启动hystrix熔断机制

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
spring:
  application:
    name: user-service   

  datasource:
    validationQuery: select 'x'
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/catj?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

