server:
  # 端口
  port: 8083

feign:
  hystrix:
    enabled: true # 启动hystrix熔断机制

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
spring:
  application:
    name: user-service

  datasource:
    validationQuery: select 'x'
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.101.141.25:3306/catj?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    useSSL: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy:  org.hibernate.cfg.ImprovedNamingStrategy

