server:
  # 端口
  port: 8083

feign:
  hystrix:
    enabled: true # 启动hystrix熔断机制

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
spring:
  application:
    name: user-service
